packages:
  - apps/*
catalog:
  typescript: ^5.8.3
  '@biomejs/biome': ^1.9.4
  '@types/node': ^20.17.50
  hono: ^4.7.10
  '@hono/node-server': ^1.14.2
  tsx: ^4.7.1
  esbuild: ^0.25.4
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
